### ISSUE TITLE
Q: Does anyone besides UMich use the VIDEO/TAPE/etc. prefixes?

### ISSUE THREAD

**Issue by billdueber** [pulibrary/lcsort#13]
I built the original regex to deal with what I was seeing in our data, not because I was at all familiar with how call numbers are supposed to be constructed (which turns out to have been a good thing, because There Are No Rules, apparently). But if no one else actually has them in their data, then they could probably be cut out.

**Comment by jpstroop** [comment]
We most certainly do (CD, DVD, MICROFILM, MICROFICHE), but they're generally followed by a shelf number (an int) which has no semantics; it just gives the thing a known place on a shelf. My guess is that the reason for removing these from the regex was that so number like this (e.g. `DVD 42`) would [get filtered out](https://github.com/pulibrary/lcsort/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R13) (I'm referring to links in PR #12 because they provide a nice diff of what's about to change and still show code that's closer to what you had initially, I think).

Are you saying that you have numbers like "VIDEO ML420 .B45" (a prefix + an actual classification number)? If so, I wonder if the `Lcsort` constructor c/should take a list of these as an option, or if `#normalize` (the class version) should take a block that injects them into each call ([this pattern](https://github.com/pulibrary/lcsort/pull/12/files#diff-3bc07058b1a05e053f7fbf71efd96ef5R125) would need to change. I think). From my blissfully-unaware-of-the-details-of-the-regex perspective, based on [this](https://github.com/pulibrary/lcsort/pull/12/files#diff-3bc07058b1a05e053f7fbf71efd96ef5L11), it doesn't seem like prepending some additional values to the front of the regex would be too difficult.

**Comment by billdueber** [comment]
We most certainly do have things with `VIDEO` as a prefix -- that's why I originally included them in the regex. If it's just us, I would say (a) remove them from the regex, and (b) just make people (e.g., me) pre-process the callnumbers before feeding them to the normalizer. 

My non-standard local content shouldn't drive a regex that has since been adopted by many other institutions. @jrochkind, thoughts?

**Comment by billdueber** [comment]
Oh, wait, I just realized that @jrochkind already took them out. So....never mind :-)

**Comment by jrochkind** [comment]
Yep, I took them out in my major overhaul fork waiting to be merged. 

My thinking it was it's trivial to trim your actual locally-specific prefixes from the call number _before_ you pass it to `Lcsort.normalize`, so there's no need for the shared code to try and guess what common locally specific prefixes might be.  

(I don't think those prefixes are from LC, they are locally specific, right? If they are standard LC prefixes that might actually be found in MARC from LC or OCLC, then it might make sense to put them back in, even though it's still trivial to remove them before passing to #normalize ?)

**Comment by jrochkind** [comment]
I also re-architected the code as an actual Object Oriented class instead of just a static method, thinking that you could provide a locally-specific sub-class with different behavior if you want -- but when I started to think about how to allow a sub-class to actually redefine the regexp in a reasonable "just override what you want to override" way, it gets tricky. There are ways to refactor to support that better, but it makes the code confusing, so I stuck to YAGNI for now. 

For just removing local prefixes, I think there's really no problem with the caller just doing it:

```
re = /\AVIDEO|AUDIO|ETC/

Lcsort.normalize( call_num.sub(re, '') )
```

I think there's no problem with the caller just doing that themselves. It shouldn't be much of a performance hit.  (Incidentally, I did benchmark, and my overhauled refactor performs about 1.5x _faster_ than the original direct port of the python code did. So we should be pretty good perf wise).

**Comment by jpstroop** [comment]
To answer your question ^^ these prefixes are a very common practice, but definitely not speced by LC anywhere.

I'm convinced by your argument. Leave as-is.

**Comment by jrochkind** [comment]
Cool. We do all sorts of OTHER weird things with our call numbers here, but don't use format prefixes like that in them, heh.
